#
# This pipeline needs the following tasks from Tekton Hub
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string

  workspaces:
    - name: pipeline-workspace

  tasks:

    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"

    - name: tests
      runAfter:
        - clone
      taskRef:
        name: echo
      params:
        - name: message
          value: "Running unit tests"

    - name: build
      runAfter:
        - lint
        - tests
      taskRef:
        name: echo
      params:
        - name: message
          value: "Building Docker image"

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: echo
      params:
        - name: message
          value: "Deploying to OpenShift"
